# Config file

# Repeated login attempts rule
# Detect login attempts from the same source
# Time window is in seconds
repeated_login:
  max_attempts: 15
  time_window: 100

# Blacklist IP rule
# List of IPs that are flagged
blacklisted_ip:
  - "192.168.1.232"
  - "172.16.0.52"

# Out of business hours rule
# Detect activity that happens outside business hours
business_hours:
  start: "4:00"
  end: "21:00"

# XSS rule
# Detect common XSS phrases
xss:
  patterns:
    - "<script>alert('xss')</script>"

# SQL injection rule
# Detect common SQL injection phrases
sql_injection:
  patterns:
    - "OR '1'='1"